<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>disable</Nullable>
    <CopyLocalLockFileAssemblies>false</CopyLocalLockFileAssemblies>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="MelonLoader">
      <Private>False</Private><HintPath>C:\Games\Survival Log\MelonLoader\net6\MelonLoader.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.CoreModule">
      <Private>False</Private><HintPath>C:\Games\Survival Log\MelonLoader\Il2CppAssemblies\UnityEngine.CoreModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.InputLegacyModule">
      <Private>False</Private><HintPath>C:\Games\Survival Log\MelonLoader\Il2CppAssemblies\UnityEngine.InputLegacyModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.IMGUIModule">
      <Private>False</Private><HintPath>C:\Games\Survival Log\MelonLoader\Il2CppAssemblies\UnityEngine.IMGUIModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.TextRenderingModule">
      <Private>False</Private><HintPath>C:\Games\Survival Log\MelonLoader\Il2CppAssemblies\UnityEngine.TextRenderingModule.dll</HintPath>
    </Reference>
    <Reference Include="Il2Cppmscorlib">
      <Private>False</Private><HintPath>C:\Games\Survival Log\MelonLoader\Il2CppAssemblies\Il2Cppmscorlib.dll</HintPath>
    </Reference>
    <Reference Include="Il2CppInterop.Runtime">
      <Private>False</Private><HintPath>C:\Games\Survival Log\MelonLoader\net6\Il2CppInterop.Runtime.dll</HintPath>
    </Reference>
  </ItemGroup>
</Project>
